name: movie_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.16
  google_nav_bar: ^5.0.7
  shimmer: ^3.0.0
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.3.3
  equatable: ^2.0.7
  flutter_bloc: ^8.1.6
  http: ^1.2.2
  flutter_dotenv: ^5.2.1
  #Firebase
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
