// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBl15abpMcuxV4pmlNf-8PlQF6M1uPRolE',
    appId: '1:859126891454:web:5e979949a0557d4898afef',
    messagingSenderId: '859126891454',
    projectId: 'movie-app-497e0',
    authDomain: 'movie-app-497e0.firebaseapp.com',
    storageBucket: 'movie-app-497e0.firebasestorage.app',
    measurementId: 'G-9FC87YSDL8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8CHhAeqtQvF9G8U0K9lo835rO3LoLdPw',
    appId: '1:859126891454:android:8871f38217f32d0f98afef',
    messagingSenderId: '859126891454',
    projectId: 'movie-app-497e0',
    storageBucket: 'movie-app-497e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGjTj9WUwqZ0Udwy8ZdceqN6ror1DZ7Q8',
    appId: '1:859126891454:ios:0f28a355faf16edd98afef',
    messagingSenderId: '859126891454',
    projectId: 'movie-app-497e0',
    storageBucket: 'movie-app-497e0.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGjTj9WUwqZ0Udwy8ZdceqN6ror1DZ7Q8',
    appId: '1:859126891454:ios:0f28a355faf16edd98afef',
    messagingSenderId: '859126891454',
    projectId: 'movie-app-497e0',
    storageBucket: 'movie-app-497e0.firebasestorage.app',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBl15abpMcuxV4pmlNf-8PlQF6M1uPRolE',
    appId: '1:859126891454:web:18b4f7eeada186e798afef',
    messagingSenderId: '859126891454',
    projectId: 'movie-app-497e0',
    authDomain: 'movie-app-497e0.firebaseapp.com',
    storageBucket: 'movie-app-497e0.firebasestorage.app',
    measurementId: 'G-5GBQ8FQW33',
  );
}
